# Change these first
owner: seedplicity # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Wiki
    url: https://wiki.seedpli.city
  - name: Website
    url: https://seedpli.city

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.seedpli.city
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Seedplicity Status
  introTitle: "**Seedplicity** is an innovative app hosting platform"
  introMessage: We engineer our platform to be as automated and resilient as possible, but life happens! If something's not right, check here first, or the [#announcements](https://discord.com/channels/907016842873278474/973461820427878410) channel in [Discord](https://discord.seedpli.city)!
  navbar:
    - title: Status
      href: /
    - title: Wiki
      href: https://wiki.seedpli.city
    - title: Discord
      href: https://discord.seedpli.city

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
